[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]

[profile.default.etherscan]
amoy = { key = "${POLYGONSCAN_API_KEY}" }

[profile.default.chains]
amoy = { chain_id = 23295 }

[profile.default.rpc_endpoints]
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"
polygon_mainnet = "${POLYGON_MAINNET_RPC_URL}"

[profile.default.env]
PRIVATE_KEY = "${PRIVATE_KEY}"