[profile.default]
src = "src"
out = "out"
libs = [ "lib" ]

[etherscan]
amoy = { key = "${POLYGONSCAN_API_KEY}" } 


[chains.amoy]
chain_id = 23295

[rpc_endpoints]
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"
polygon_mainnet = "${POLYGON_MAINNET_RPC_URL}"


[env]
PRIVATE_KEY = "${PRIVATE_KEY}"
