[profile.default]
src = "src"
out = "out"
libs = [ "lib" ]


[rpc_endpoints]
polygon_amoy = "${POLYGON_AMOY_RPC_URL}"
polygon_mainnet = "${POLYGON_MAINNET_RPC_URL}"


[env]
PRIVATE_KEY = "${PRIVATE_KEY}"
